spring:
  application:
    name: order-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ${CLOUD_SERVICE_ID}
  docker:
    compose:
      lifecycle-management: start_only
eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

rabbit:
  stock:
    exchange: stock.exchange
    registered:
      routing-key: stock.registered
      queue: stock.registered.queue
    decreased:
      routing-key: stock.decreased
      queue: stock.decreased.queue
    decrease-fail:
      routing-key: stock.decrease.fail
      queue: stock.decreased.fail.queue
  order:
    exchange: order.exchange
    created:
      routing-key: order.created
      queue: order.created.queue